// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwHCXRsoGmq5UerRattssqGEwpadK3txA',
    appId: '1:866344199872:web:c5cb9da916a709e0666f25',
    messagingSenderId: '866344199872',
    projectId: 'captin-care',
    authDomain: 'captin-care.firebaseapp.com',
    storageBucket: 'captin-care.firebasestorage.app',
    measurementId: 'G-9XJB79TTQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9XpmxqqULxQxk2IGGZJ_hJieIIxJWvzY',
    appId: '1:866344199872:android:97c5565fdc1a206f666f25',
    messagingSenderId: '866344199872',
    projectId: 'captin-care',
    storageBucket: 'captin-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoSmanQIgPr9IGh2y4ze-IQPR1sMmst0U',
    appId: '1:866344199872:ios:ffafdfdc1b156cd8666f25',
    messagingSenderId: '866344199872',
    projectId: 'captin-care',
    storageBucket: 'captin-care.firebasestorage.app',
    iosBundleId: 'com.example.captinCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoSmanQIgPr9IGh2y4ze-IQPR1sMmst0U',
    appId: '1:866344199872:ios:ffafdfdc1b156cd8666f25',
    messagingSenderId: '866344199872',
    projectId: 'captin-care',
    storageBucket: 'captin-care.firebasestorage.app',
    iosBundleId: 'com.example.captinCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwHCXRsoGmq5UerRattssqGEwpadK3txA',
    appId: '1:866344199872:web:949291e952b03f27666f25',
    messagingSenderId: '866344199872',
    projectId: 'captin-care',
    authDomain: 'captin-care.firebaseapp.com',
    storageBucket: 'captin-care.firebasestorage.app',
    measurementId: 'G-FLP2KD1JQN',
  );
}
